#!/usr/bin/env bash

# Parsing tsv annotated file generated by launch_ProtVar.sh
# Example execution line:
# ./parse_AnnotProtVar.sh input_file

# Variables
input_file=$1

#########################################################
##  PARSING ANNOTATIONS
#########################################################

# Interesting fields
#      1  User_input -> 
#      2  Chromosome ->
#      3  Coordinate ->
#      5  Reference_allele ->
#      6  Alternative_allele ->
#      8  Gene ->
#      9  Codon_change ->
#     14  Uniprot_canonical_isoform_(non_canonical) ->
#     17  Amino_acid_position ->
#     18  Amino_acid_change ->
#     19  Consequences ->
#     20  Residue_function_(evidence) ->
#     21  Region_function_(evidence) ->
#     30  Protein_interactions_PROTEIN(gene) ->
#     31  Predicted_pockets(energy;per_vol;score;resids)  ->  degree of confidence in the existence of the pocket containing the variant (>900 very high; 800-900 high; <800 low) / More than one score per line is possible
#     33  Foldx_prediction(foldxDdg;plddt)  -> Alphafold prediction (foldx: stability / plddt: confidence)
#     34  Conservation_score  ->  [0-1] -> 1(very highly conserved)
#     35  AlphaMissense_pathogenicity(class)  ->
#     36  popEVE_score(class)  ->
#     37  ESM1b_score  ->
#     42  Diseases_associated_with_variant  ->


if [ -n "$2" ]; then
    output_file="$2"
else
    DIRNAME=$(dirname "$input_file")
    BASENAME=$(basename "$input_file")
    if [ "$DIRNAME" = "." ]; then
        output_file="ProtVarAnnot_${BASENAME}"
    else
        output_file="${DIRNAME}/ProtVarAnnot_${BASENAME}"
    fi
fi

awk -F'\t' 'BEGIN { OFS="\t" }
{
    # 1. Skip the original header and print the custom header
    if (NR == 1) {
        print "user_variant", "grch38_coord", "gene", "uniprot_id", "consequence", "codon_change", "aa_acid_change", "residue_function", "region_function", "interactions_genes", "pocket_label", "alphafold-foldxDdg", "alphafold-plddt", "conservation", "alphamissense", "popeve", "esm1b", "diseases"
        next
    }

    # 2. Extract fields (awk is 1-indexed)
    user_variant = $1
    grch38_coord = $2 ":" $3 ":" $5 ":" $6
    gene = $8
    uniprot_id = $14
    consequence = $19
    codon_change = $9
    aa_acid_position = $17
    aa_acid_change = $18
    
    aa_acid_change_4manual = "p." aa_acid_change
    gsub("/", aa_acid_position, aa_acid_change_4manual)
    
    residue_function = $20
    region_function = $21
    
    # Interactions genes (extracting content inside parentheses)
    interactions_genes = ""
    str = $30
    while (match(str, /\(([^)]+)\)/)) {
        val = substr(str, RSTART+1, RLENGTH-2)
        interactions_genes = (interactions_genes == "") ? val : interactions_genes "," val
        str = substr(str, RSTART+RLENGTH)
    }
    if (interactions_genes == "") interactions_genes = "-"
    
    # Pocket labels (extracting score:X)
    pocket_str = $31
    pocket_label = ""
    while (match(pocket_str, /score:([0-9.]+)/)) {
        val = substr(pocket_str, RSTART+6, RLENGTH-6) + 0
        if (val > 900) l = "very high"
        else if (val >= 800) l = "high"
        else l = "low"
        
        pocket_label = (pocket_label == "") ? l : pocket_label ";" l
        pocket_str = substr(pocket_str, RSTART+RLENGTH)
    }
    if (pocket_label == "") pocket_label = "-"
    
    # AlphaFold foldxDdg and plddt labels
    alphafold = $33
    foldxDdg_label = ""
    plddt_label = ""
    
    af_str = alphafold
    while (match(af_str, /foldxDdg:(-?[0-9.]+)/)) {
        val = substr(af_str, RSTART+9, RLENGTH-9) + 0
        l = (val > 2) ? "destabilising" : "stabilising/neutral"
        foldxDdg_label = (foldxDdg_label == "") ? l : foldxDdg_label ";" l
        af_str = substr(af_str, RSTART+RLENGTH)
    }
    if (foldxDdg_label == "") foldxDdg_label = "-"
    
    af_str = alphafold
    while (match(af_str, /plddt:(-?[0-9.]+)/)) {
        val = substr(af_str, RSTART+6, RLENGTH-6) + 0
        if (val > 90) l = "Very high"
        else if (val > 70) l = "High"
        else if (val > 50) l = "Low"
        else l = "Very low"
        plddt_label = (plddt_label == "") ? l : plddt_label ";" l
        af_str = substr(af_str, RSTART+RLENGTH)
    }
    if (plddt_label == "") plddt_label = "-"
    
    conservation = $34
    if (conservation == "") conservation = "-"
    
    # AlphaMissense (extracting content inside parentheses)
    alphamissense = "-"
    if (match($35, /\(([^)]+)\)/)) {
        alphamissense = substr($35, RSTART+1, RLENGTH-2)
    }
    
    # popEVE (extracting content inside parentheses)
    popeve = "-"
    if (match($36, /\(([^)]+)\)/)) {
        popeve = substr($36, RSTART+1, RLENGTH-2)
    }
    
    # ESM1b score label
    esm1b_val = $37
    if (esm1b_val == "" || esm1b_val == "-") {
        esm1b_label = "-"
    } else {
        val = esm1b_val + 0
        if (val <= 0 && val >= -5) esm1b_label = "benign"
        else if (val < -5 && val >= -10) esm1b_label = "uncertain"
        else if (val < -10 && val >= -25) esm1b_label = "pathogenic"
        else esm1b_label = "-"
    }
    
    # Diseases
    diseases = $42
    gsub("N/A", "-", diseases)
    if (diseases == "") diseases = "-"
    
    # Print the parsed line
    print user_variant, grch38_coord, gene, uniprot_id, consequence, codon_change, aa_acid_change_4manual, residue_function, region_function, interactions_genes, pocket_label, foldxDdg_label, plddt_label, conservation, alphamissense, popeve, esm1b_label, diseases

}' "$input_file" > "$output_file"

echo "Parsing completed: ${output_file}"