#!/usr/bin/env bash

# Parsing tsv annotated file generated by launch_ProtVar.sh
# Example execution line:
# ./parse_AnnotProtVar.sh input_file

# Variables
input_file=$1

#########################################################
##  PARSING ANNOTATIONS
#########################################################

# Interesting fields
#      1  User_input -> 
#      2  Chromosome ->
#      3  Coordinate ->
#      5  Reference_allele ->
#      6  Alternative_allele ->
#      8  Gene ->
#      9  Codon_change ->
#     14  Uniprot_canonical_isoform_(non_canonical) ->
#     17  Amino_acid_position ->
#     18  Amino_acid_change ->
#     19  Consequences ->
#     20  Residue_function_(evidence) ->
#     21  Region_function_(evidence) ->
#     30  Protein_interactions_PROTEIN(gene) ->
#     31  Predicted_pockets(energy;per_vol;score;resids)  ->  degree of confidence in the existence of the pocket containing the variant (>900 very high; 800-900 high; <800 low) / More than one score per line is possible
#     33  Foldx_prediction(foldxDdg;plddt)  -> Alphafold prediction (foldx: stability / plddt: confidence)
#     34  Conservation_score  ->  [0-1] -> 1(very highly conserved)
#     35  AlphaMissense_pathogenicity(class)  ->
#     36  popEVE_score(class)  ->
#     37  ESM1b_score  ->
#     42  Diseases_associated_with_variant  ->


if [ -n "$2" ]; then
    output_file="$2"
else
    DIRNAME=$(dirname "$input_file")
    BASENAME=$(basename "$input_file")
    if [ "$DIRNAME" = "." ]; then
        output_file="ProtVarAnnot_${BASENAME}"
    else
        output_file="${DIRNAME}/ProtVarAnnot_${BASENAME}"
    fi
fi

while read line; do 

    user_variant=`echo "${line}" | cut -f 1`
    grch38_coord=`echo "${line}" | cut -f 2,3,5,6 | sed 's/\t/:/g'`
    gene=`echo "${line}" | cut -f 8`
    uniprot_id=`echo "${line}" | cut -f 14`
    consequence=`echo "${line}" | cut -f 19`
    codon_change=`echo "${line}" | cut -f 9`
    aa_acid_position=`echo "${line}" | cut -f 17`
    aa_acid_change=`echo "${line}" | cut -f 18`
    aa_acid_change_4manual=`echo -e "p.${aa_acid_change}" | sed "s/\//${aa_acid_position}/g"`
    residue_function=`echo "${line}" | cut -f 20`
    region_function=`echo "${line}" | cut -f 21`
    interactions_genes=`echo "${line}" | cut -f 30 | sed -E 's/[^()]*\(([^)]+)\)[^()]*/\1,/g; s/,$//'`
    pocket_value=$(echo "${line}" | cut -f 31 | grep -oP 'score:\K[0-9.]+' | tr '\n' ';' | sed 's/;$//')
    pocket_value=${pocket_value:-"-"}
    pocket_label=$(echo "$pocket_value" | awk -F';' '{for(i=1;i<=NF;i++) {if($i=="-" || $i=="") printf "-"; else if($i>900) printf "very high"; else if($i>=800) printf "high"; else printf "low"; if(i<NF) printf ";"}; print ""}')
    alphafold=`echo "${line}" | cut -f 33`
    foldxDdg=$(echo "$alphafold" | grep -oE 'foldxDdg:-?[0-9.]+' | cut -d':' -f2 | paste -sd ';' -); [ -z "$foldxDdg" ] && foldxDdg="-"
    plddt=$(echo "$alphafold" | grep -oE 'plddt:-?[0-9.]+' | cut -d':' -f2 | paste -sd ';' -); [ -z "$plddt" ] && plddt="-"
    foldxDdg_label=$(echo "$foldxDdg" | awk -F';' '$1=="-"{print "-";next} {for(i=1;i<=NF;i++) printf "%s%s", ($i>2?"destabilising":"stabilising/neutral"), (i==NF?ORS:";")}')
    plddt_label=$(echo "$plddt" | awk -F';' '$1=="-"{print "-";next} {for(i=1;i<=NF;i++) {l=($i>90?"Very high":($i>70?"High":($i>50?"Low":"Very low"))); printf "%s%s", l, (i==NF?ORS:";")}}')
    conservartion=`echo "${line}" | cut -f 34`
    alphamissense=`echo "${line}" | cut -f 35 | sed -n 's/.*(\(.*\))/\1/p'`
    alphamissense=${alphamissense:-"-"}
    popeve=`echo "${line}" | cut -f 36 | sed -n 's/.*(\(.*\))/\1/p'`  
    popeve=${popeve:-"-"}
    esm1b_value=`echo "${line}" | cut -f 37`
    esm1b_label=$(echo "$esm1b_value" | awk '{val=$1; if(val == "" || val == "-") {print "-"} else if(val <= 0 && val >= -5) {print "benign"} else if(val < -5 && val >= -10) {print "uncertain"} else if(val < -10 && val >= -25) {print "pathogenic"} else {print "-"}}')
    diseases=`echo "${line}" | cut -f 42 | sed 's/N\/A/-/g'`

    echo -e "${user_variant}\t${grch38_coord}\t${gene}\t${uniprot_id}\t${consequence}\t${codon_change}\t${aa_acid_change_4manual}\t${residue_function}\t${region_function}\t${interactions_genes}\t${pocket_label}\t${foldxDdg_label}\t${plddt_label}\t${conservartion}\t${alphamissense}\t${popeve}\t${esm1b_label}\t${diseases}"

done < "${input_file}" > "${output_file}"


# Modify header
sed -i '1d' "${output_file}"
sed -i "1s/^/user_variant\\tgrch38_coord\\tgene\\tuniprot_id\\tconsequence\\tcodon_change\\taa_acid_change\\tresidue_function\\tregion_function\\tinteractions_genes\\tpocket_label\\talphafold-foldxDdg\\talphafold-plddt\\tconservation\\talphamissense\\tpopeve\\tesm1b\\tdiseases\\n/" "${output_file}"

echo "Parsing completed: ${output_file}"